extends:
  - ../base.yaml
  - ../../data/re10k.yaml

model:
  backbone:
    config_path: configs/mvp/inference_re10k_224.yaml
    freeze: true

wandb:
  tags: [posed, mvp, 3d-token, re10k, 2-view, "224"]
