extends: ../base.yaml

model:
  backbone:
    config_path: configs/mvp/inference_re10k_224.yaml

data:
  root: datasets/re10k
  stage: train
  image_size: [224, 224]
  original_image_size: [360, 640]
  num_context_views: 2
  num_target_views: 4
  min_context_gap: 45
  max_context_gap: 90
  min_target_distance: 0
  baseline_min: 1.0e-3
  baseline_max: 1.0e10
  max_fov: 100.0
  make_baseline_one: true
  relative_pose: true
  augment: true
  skip_bad_shape: true
  seed: 42

training:
  dataset_name: data.re10k_dataset.RE10KDataset
  num_views: [2]
  target_views: [4]
  res_dict: [[224, 224]]
  batch_size_per_gpu: [4]
  num_workers: 8
  prefetch_factor: 2

wandb:
  tags: [posed, mvp, 3d-token, re10k, 2-view, 224]
