extends: train_init.yaml

model:
  decoder:
    split:
      enabled: false
    refinement:
      layers: []

training:
  checkpoint_dir: ./experiments/checkpoints/3d_token_e00

wandb:
  name: 3D_Token_MVP_E00_Fixed_2K
