extends: train_full.yaml

model:
  decoder:
    split:
      enabled: true
      dense: true
    refinement:
      layers: []

training:
  checkpoint_dir: ./experiments/checkpoints/3d_token_e01

wandb:
  name: 3D_Token_MVP_E01_Latent_Split
