extends: train_full.yaml

model:
  decoder:
    split:
      enabled: true
      dense: true
    refinement:
      layers:
        - type: cross
          repeat: 2
        - type: slot
          repeat: 2

training:
  checkpoint_dir: ./experiments/checkpoints/3d_token_e02

wandb:
  name: 3D_Token_MVP_E02_Refinement
