extends: base.yaml

model:
  decoder:
    split:
      enabled: true
      dense: true
    refinement:
      layers:
        - type: cross
          repeat: 2
        - type: slot
          repeat: 2

training:
  stage: full
  initialization_checkpoint: ./experiments/checkpoints/3d_token_init
  checkpoint_dir: ./experiments/checkpoints/3d_token_full

wandb:
  name: 3D_Token_MVP_Full
  tags: [posed, mvp, 3d-token, full]
