extends:
  - inference_base.yaml
  - ../data/re10k.yaml

model:
  input_image_size: [224, 224]
  group_size: 2

data:
  stage: test
  pose_normalization: mvp
  make_baseline_one: false
  relative_pose: false
  augment: false

inference:
  dataset_name: data.re10k_dataset.RE10KDataset
  prefetch_factor: 2
  max_batches: 10
  out_dir: ./experiments/inference_mvp_re10k_2view_224
