extends:
  - inference_base.yaml
  - ../data/dl3dv.yaml

data:
  data_path: data/dl3dv_benchmark.txt
  resize_h: 540
  random_crop: 1.0
  input_frame_select_type: kmeans
  target_frame_select_type: uniform_every
  num_input_frames: 16
  num_target_frames: 0
  target_has_input: false
  max_frame_dist: 256
  reverse_input_prob: 0.0
  target_uniform_every: 8

inference:
  dataset_name: data.mvp_dataset.Dataset
  out_dir: ./experiments/inference
